const products = [
  // Ape
  {id: 1, productName: 'ApeXplorer',image:'/img/navBarImg.png', price: 500,category: 'Ape', imgBanner: '/img/navBarImg.png',description: 'ApeXplorer es un NFT de un mono explorador, que se encuentra en la selva, es un mono muy curioso y le encanta explorar, es un NFT muy especial y único, ya que es el primer NFT de la colección de monos exploradores.'},
  {id: 2, productName: 'CosmicApe',image:'/img/ape-2.png', price: 800,category: 'Ape',description: 'ApeXplorer es un NFT de un mono explorador, que se encuentra en la selva, es un mono muy curioso y le encanta explorar, es un NFT muy especial y único, ya que es el primer NFT de la colección de monos exploradores.'},
  {id: 3, productName: 'JungleApe',image:'/img/ape-3.png', price: 630,category: 'Ape',description: 'ApeXplorer es un NFT de un mono explorador, que se encuentra en la selva, es un mono muy curioso y le encanta explorar, es un NFT muy especial y único, ya que es el primer NFT de la colección de monos exploradores.'},
  {id: 4, productName: 'UrbanApe',image:'/img/ape-4.avif', price: 1360,category: 'Ape',description: 'ApeXplorer es un NFT de un mono explorador, que se encuentra en la selva, es un mono muy curioso y le encanta explorar, es un NFT muy especial y único, ya que es el primer NFT de la colección de monos exploradores.'},
  {id: 5, productName: 'CyberApe',image:'/img/ape-4.jpeg', price: 1420,category: 'Ape',description: 'ApeXplorer es un NFT de un mono explorador, que se encuentra en la selva, es un mono muy curioso y le encanta explorar, es un NFT muy especial y único, ya que es el primer NFT de la colección de monos exploradores.'},
  // Metaverse
  {id: 6, productName: 'MetaMonarch',image:'/img/metaverseKing-1.avif', price: 320,category: 'Metaverse', description: 'MetaMonarch es un NFT de un rey del metaverso, es un rey muy poderoso y sabio, es un NFT muy especial y único, ya que es el primer NFT de la colección de reyes del metaverso.'},
  {id: 7, productName: 'VirtualSovereign',image:'/img/metaverseKing-2.avif', price: 150,category: 'Metaverse', description: 'MetaMonarch es un NFT de un rey del metaverso, es un rey muy poderoso y sabio, es un NFT muy especial y único, ya que es el primer NFT de la colección de reyes del metaverso.'},
  {id: 8, productName: 'KingdomMeta',image:'/img/metaverseKing-3.jpeg', price: 3400,category: 'Metaverse', description: 'MetaMonarch es un NFT de un rey del metaverso, es un rey muy poderoso y sabio, es un NFT muy especial y único, ya que es el primer NFT de la colección de reyes del metaverso.'},
  {id: 9, productName: 'RulerOfRealms',image:'/img/metaverseKing-4.jpeg', price: 2200,category: 'Metaverse', description: 'MetaMonarch es un NFT de un rey del metaverso, es un rey muy poderoso y sabio, es un NFT muy especial y único, ya que es el primer NFT de la colección de reyes del metaverso.'},
  {id: 10, productName: 'MetaMajesty',image:'/img/metaverseKing-5.webp', price: 950,category: 'Metaverse', description: 'MetaMonarch es un NFT de un rey del metaverso, es un rey muy poderoso y sabio, es un NFT muy especial y único, ya que es el primer NFT de la colección de reyes del metaverso.'},
  // Godness
  {id: 11, productName: 'DivineEssence',image:'/img/godness-1.png', price: 560,category: 'Godness', description: 'DivineEssence es un NFT de una diosa, es una diosa muy poderosa y sabia, es un NFT muy especial y único, ya que es el primer NFT de la colección de diosas.'},
  {id: 12, productName: 'EtherealDeity',image:'/img/godness-2.jpeg', price: 90,category: 'Godness', description: 'DivineEssence es un NFT de una diosa, es una diosa muy poderosa y sabia, es un NFT muy especial y único, ya que es el primer NFT de la colección de diosas.'},
  {id: 13, productName: 'SacredSeraph',image:'/img/godness-3.jpeg', price: 4200,category: 'Godness', description: 'DivineEssence es un NFT de una diosa, es una diosa muy poderosa y sabia, es un NFT muy especial y único, ya que es el primer NFT de la colección de diosas.'},
  {id: 14, productName: 'CelestialGoddess',image:'/img/godness-4.jpeg', price: 5500,category: 'Godness', description: 'DivineEssence es un NFT de una diosa, es una diosa muy poderosa y sabia, es un NFT muy especial y único, ya que es el primer NFT de la colección de diosas.'},
  {id: 15, productName: 'MythicDivinity',image:'/img/godness-5.webp', price: 180,category: 'Godness', description: 'DivineEssence es un NFT de una diosa, es una diosa muy poderosa y sabia, es un NFT muy especial y único, ya que es el primer NFT de la colección de diosas.'},
  // Mocaverse
  {id: 16, productName: 'MocaVoyager',image:'/img/mocaverse-1.png', price: 920,category: 'Mocaverse', description: 'MocaVoyager es un NFT de un viajero del mocaverso, es un viajero muy aventurero y curioso, es un NFT muy especial y único, ya que es el primer NFT de la colección de viajeros del mocaverso.'},
  {id: 17, productName: 'CosmoMoca',image:'/img/mocaverse-2.png', price: 710,category: 'Mocaverse', description: 'MocaVoyager es un NFT de un viajero del mocaverso, es un viajero muy aventurero y curioso, es un NFT muy especial y único, ya que es el primer NFT de la colección de viajeros del mocaverso.'},
  {id: 18, productName: 'MocaRealm',image:'/img/mocaverse-3.webp', price: 4530,category: 'Mocaverse', description: 'MocaVoyager es un NFT de un viajero del mocaverso, es un viajero muy aventurero y curioso, es un NFT muy especial y único, ya que es el primer NFT de la colección de viajeros del mocaverso.'},
  {id: 19, productName: 'StellarMoca',image:'/img/mocaverse-4.webp', price: 1820,category: 'Mocaverse', description: 'MocaVoyager es un NFT de un viajero del mocaverso, es un viajero muy aventurero y curioso, es un NFT muy especial y único, ya que es el primer NFT de la colección de viajeros del mocaverso.'},
  {id: 20, productName: 'MocaOdyssey',image:'/img/mocaverse-5.avif', price: 490,category: 'Mocaverse', description: 'MocaVoyager es un NFT de un viajero del mocaverso, es un viajero muy aventurero y curioso, es un NFT muy especial y único, ya que es el primer NFT de la colección de viajeros del mocaverso.'},
];